### ISSUE TITLE
 strings.xml 里有product时, 编译报 more than one time

### ISSUE THREAD

**Issue by Songsayit** [siren-ocean/Settings#1]
系统设置里的 strings.xml 有些是有 product 选项的,比如
  <string name="power_remaining_duration_only_shutdown_imminent" product="default">Phone may shut down soon</string>
  <string name="power_remaining_duration_only_shutdown_imminent" product="tablet">Tablet may shut down soon</string>
  <string name="power_remaining_duration_only_shutdown_imminent" product="device">Device may shut down soon</string>

这个会在 AS里报  more than one time 编译错误.  你那边有遇到的吗

**Comment by siren-ocean** [comment]
跑一下Filter的main方法，右键run一下，它会替你过滤掉这些属性
